# Generated by Django 5.2.5 on 2025-11-11 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120)),
                ('capacidad_diaria', models.PositiveIntegerField(default=12)),
                ('activo', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicia_en', models.DateTimeField()),
                ('termina_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No Asiste'), ('ATENDIDA', 'Atendida')], default='AGENDADA', max_length=10)),
                ('token_confirmacion', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipotratamiento')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.odontologo')),
            ],
            options={
                'indexes': [models.Index(fields=['paciente', 'inicia_en'], name='agenda_cita_pacient_c1d5af_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('termina_en__gt', models.F('inicia_en'))), name='cita_fin_despues_inicio'), models.UniqueConstraint(fields=('odontologo', 'inicia_en'), name='uniq_cita_odontologo_inicio')],
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicia_en', models.DateTimeField()),
                ('termina_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADO', 'Reservado'), ('AGENDADO', 'Agendado')], default='LIBRE', max_length=9)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.especialidad')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.odontologo')),
            ],
            options={
                'indexes': [models.Index(fields=['odontologo', 'inicia_en', 'estado'], name='agenda_bloq_odontol_3c0110_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('termina_en__gt', models.F('inicia_en'))), name='bloque_fin_despues_inicio'), models.UniqueConstraint(fields=('odontologo', 'inicia_en'), name='uniq_bloque_odontologo_inicio')],
            },
        ),
    ]
