# Generated by Django 5.2.5 on 2025-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('comuna', models.CharField(blank=True, max_length=80)),
                ('contacto_alt_nombre', models.CharField(blank=True, max_length=120)),
                ('contacto_alt_parentesco', models.CharField(blank=True, max_length=40)),
                ('contacto_alt_telefono', models.CharField(blank=True, max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='pacientes_p_apellid_110dbb_idx')],
            },
        ),
    ]
