# Generated by Django 5.2.5 on 2025-11-11 01:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivado_en', models.DateField()),
                ('prioridad_clinica', models.CharField(choices=[('P1', 'Alta'), ('P2', 'Media'), ('P3', 'Baja')], max_length=2)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AGENDADO', 'Agendado'), ('REMOVIDO', 'Removido')], default='PENDIENTE', max_length=10)),
                ('puntaje', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('puntaje_actualizado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipotratamiento')),
            ],
            options={
                'verbose_name': 'Entrada de Lista de Espera',
                'verbose_name_plural': 'Entradas de Lista de Espera',
                'indexes': [models.Index(fields=['tratamiento', 'estado', '-puntaje', 'derivado_en'], name='espera_entr_tratami_336a1c_idx')],
            },
        ),
    ]
