# Generated by Django 5.2.5 on 2025-12-15 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradalistaespera',
            name='derivado_en',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
